version: "3"

services:
  frontend:
    container_name: app_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    image: 541795963971.dkr.ecr.us-east-2.amazonaws.com/levelup-everyday-frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/usr/src/app/src"

    command: "npm start"

  backend:
    container_name: app_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    image: 541795963971.dkr.ecr.us-east-2.amazonaws.com/levelup-everyday-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/svr/app
      - /svr/app/node_modules

    environment:
      MONGO_URI: mongodb+srv://admin:Qorrha9441@levelup-everyday.yhbj2.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      SECRETKEY: fsdgsdghwewe
      SWAGGER_USER: levelup_admin
      SWAGGER_PASSWORD: skygoup!@
      AUTHOR_EMAIL: test_admin@gmail.com
