version: "3"
x-aws-vpc: "vpc-4166f12a"
services:
  frontend:
    container_name: app_frontend
    # image: 541795963971.dkr.ecr.ap-northeast-2.amazonaws.com/levelup-everyday-client:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - "3000:80"
    volumes:
      - "./frontend/src:/usr/src/app/src"

  backend:
    container_name: app_backend
    # image: 541795963971.dkr.ecr.ap-northeast-2.amazonaws.com/levelup-everyday-server:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/svr/app
      - /svr/app/node_modules

    environment:
      MONGO_URI: mongodb+srv://admin:Qorrha9441@levelup-everyday.yhbj2.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      SECRETKEY: fsdgsdghwewe
      SWAGGER_USER: levelup_admin
      SWAGGER_PASSWORD: skygoup!@
      AUTHOR_EMAIL: test_admin@gmail.com

networks:
  backend:
    driver: bridge
